/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedVaccinationsRouteImport } from './routes/_authenticated/vaccinations'
import { Route as AuthenticatedTelemedicineRouteImport } from './routes/_authenticated/telemedicine'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPaymentsOnlineRouteImport } from './routes/_authenticated/payments-online'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedOtRouteImport } from './routes/_authenticated/ot'
import { Route as AuthenticatedOpdRouteImport } from './routes/_authenticated/opd'
import { Route as AuthenticatedNurseStationRouteImport } from './routes/_authenticated/nurse-station'
import { Route as AuthenticatedLaboratoryRouteImport } from './routes/_authenticated/laboratory'
import { Route as AuthenticatedIpdRouteImport } from './routes/_authenticated/ipd'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedHealthRecordsRouteImport } from './routes/_authenticated/health-records'
import { Route as AuthenticatedHealthPackagesRouteImport } from './routes/_authenticated/health-packages'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAmbulanceRouteImport } from './routes/_authenticated/ambulance'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedPharmacyIndexRouteImport } from './routes/_authenticated/pharmacy.index'
import { Route as AuthenticatedLaboratoryIndexRouteImport } from './routes/_authenticated/laboratory.index'
import { Route as AuthenticatedIpdIndexRouteImport } from './routes/_authenticated/ipd.index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing.index'
import { Route as PrescriptionsIdPrintRouteImport } from './routes/prescriptions.$id.print'
import { Route as DischargeIdPrintRouteImport } from './routes/discharge.$id.print'
import { Route as AuthenticatedPharmacyMedicinesRouteImport } from './routes/_authenticated/pharmacy.medicines'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients.new'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedOpdAppointmentIdRouteImport } from './routes/_authenticated/opd.$appointmentId'
import { Route as AuthenticatedLaboratoryTestsRouteImport } from './routes/_authenticated/laboratory.tests'
import { Route as AuthenticatedLaboratoryNewRouteImport } from './routes/_authenticated/laboratory.new'
import { Route as AuthenticatedLaboratoryIdRouteImport } from './routes/_authenticated/laboratory.$id'
import { Route as AuthenticatedIpdNewRouteImport } from './routes/_authenticated/ipd.new'
import { Route as AuthenticatedIpdBedsRouteImport } from './routes/_authenticated/ipd.beds'
import { Route as AuthenticatedIpdIdRouteImport } from './routes/_authenticated/ipd.$id'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr.payroll'
import { Route as AuthenticatedHrLeaveRouteImport } from './routes/_authenticated/hr.leave'
import { Route as AuthenticatedHrEmployeesRouteImport } from './routes/_authenticated/hr.employees'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr.attendance'
import { Route as AuthenticatedBillingNewRouteImport } from './routes/_authenticated/billing.new'
import { Route as AuthenticatedBillingIdRouteImport } from './routes/_authenticated/billing.$id'
import { Route as AuthenticatedPharmacySalesNewRouteImport } from './routes/_authenticated/pharmacy.sales.new'
import { Route as AuthenticatedIpdIdDischargeRouteImport } from './routes/_authenticated/ipd.$id.discharge'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaccinationsRoute =
  AuthenticatedVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTelemedicineRoute =
  AuthenticatedTelemedicineRouteImport.update({
    id: '/telemedicine',
    path: '/telemedicine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsOnlineRoute =
  AuthenticatedPaymentsOnlineRouteImport.update({
    id: '/payments-online',
    path: '/payments-online',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOtRoute = AuthenticatedOtRouteImport.update({
  id: '/ot',
  path: '/ot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpdRoute = AuthenticatedOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNurseStationRoute =
  AuthenticatedNurseStationRouteImport.update({
    id: '/nurse-station',
    path: '/nurse-station',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLaboratoryRoute = AuthenticatedLaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpdRoute = AuthenticatedIpdRouteImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRecordsRoute =
  AuthenticatedHealthRecordsRouteImport.update({
    id: '/health-records',
    path: '/health-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHealthPackagesRoute =
  AuthenticatedHealthPackagesRouteImport.update({
    id: '/health-packages',
    path: '/health-packages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAmbulanceRoute = AuthenticatedAmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyIndexRoute =
  AuthenticatedPharmacyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPharmacyRoute,
  } as any)
const AuthenticatedLaboratoryIndexRoute =
  AuthenticatedLaboratoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedIpdIndexRoute = AuthenticatedIpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const PrescriptionsIdPrintRoute = PrescriptionsIdPrintRouteImport.update({
  id: '/prescriptions/$id/print',
  path: '/prescriptions/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const DischargeIdPrintRoute = DischargeIdPrintRouteImport.update({
  id: '/discharge/$id/print',
  path: '/discharge/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPharmacyMedicinesRoute =
  AuthenticatedPharmacyMedicinesRouteImport.update({
    id: '/medicines',
    path: '/medicines',
    getParentRoute: () => AuthenticatedPharmacyRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPatientsRoute,
} as any)
const AuthenticatedOpdAppointmentIdRoute =
  AuthenticatedOpdAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AuthenticatedOpdRoute,
  } as any)
const AuthenticatedLaboratoryTestsRoute =
  AuthenticatedLaboratoryTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedLaboratoryNewRoute =
  AuthenticatedLaboratoryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedLaboratoryIdRoute =
  AuthenticatedLaboratoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedIpdNewRoute = AuthenticatedIpdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIpdBedsRoute = AuthenticatedIpdBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIpdIdRoute = AuthenticatedIpdIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrLeaveRoute = AuthenticatedHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrEmployeesRoute =
  AuthenticatedHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingNewRoute = AuthenticatedBillingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBillingRoute,
} as any)
const AuthenticatedBillingIdRoute = AuthenticatedBillingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBillingRoute,
} as any)
const AuthenticatedPharmacySalesNewRoute =
  AuthenticatedPharmacySalesNewRouteImport.update({
    id: '/sales/new',
    path: '/sales/new',
    getParentRoute: () => AuthenticatedPharmacyRoute,
  } as any)
const AuthenticatedIpdIdDischargeRoute =
  AuthenticatedIpdIdDischargeRouteImport.update({
    id: '/discharge',
    path: '/discharge',
    getParentRoute: () => AuthenticatedIpdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ambulance': typeof AuthenticatedAmbulanceRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/bi': typeof AuthenticatedBiRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/branches': typeof AuthenticatedBranchesRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/health-packages': typeof AuthenticatedHealthPackagesRoute
  '/health-records': typeof AuthenticatedHealthRecordsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/ipd': typeof AuthenticatedIpdRouteWithChildren
  '/laboratory': typeof AuthenticatedLaboratoryRouteWithChildren
  '/nurse-station': typeof AuthenticatedNurseStationRoute
  '/opd': typeof AuthenticatedOpdRouteWithChildren
  '/ot': typeof AuthenticatedOtRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/payments-online': typeof AuthenticatedPaymentsOnlineRoute
  '/pharmacy': typeof AuthenticatedPharmacyRouteWithChildren
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/billing/$id': typeof AuthenticatedBillingIdRoute
  '/billing/new': typeof AuthenticatedBillingNewRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/ipd/$id': typeof AuthenticatedIpdIdRouteWithChildren
  '/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/ipd/new': typeof AuthenticatedIpdNewRoute
  '/laboratory/$id': typeof AuthenticatedLaboratoryIdRoute
  '/laboratory/new': typeof AuthenticatedLaboratoryNewRoute
  '/laboratory/tests': typeof AuthenticatedLaboratoryTestsRoute
  '/opd/$appointmentId': typeof AuthenticatedOpdAppointmentIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/pharmacy/medicines': typeof AuthenticatedPharmacyMedicinesRoute
  '/discharge/$id/print': typeof DischargeIdPrintRoute
  '/prescriptions/$id/print': typeof PrescriptionsIdPrintRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/ipd/': typeof AuthenticatedIpdIndexRoute
  '/laboratory/': typeof AuthenticatedLaboratoryIndexRoute
  '/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
  '/ipd/$id/discharge': typeof AuthenticatedIpdIdDischargeRoute
  '/pharmacy/sales/new': typeof AuthenticatedPharmacySalesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ambulance': typeof AuthenticatedAmbulanceRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/bi': typeof AuthenticatedBiRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/health-packages': typeof AuthenticatedHealthPackagesRoute
  '/health-records': typeof AuthenticatedHealthRecordsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/nurse-station': typeof AuthenticatedNurseStationRoute
  '/opd': typeof AuthenticatedOpdRouteWithChildren
  '/ot': typeof AuthenticatedOtRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/payments-online': typeof AuthenticatedPaymentsOnlineRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/billing/$id': typeof AuthenticatedBillingIdRoute
  '/billing/new': typeof AuthenticatedBillingNewRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/ipd/$id': typeof AuthenticatedIpdIdRouteWithChildren
  '/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/ipd/new': typeof AuthenticatedIpdNewRoute
  '/laboratory/$id': typeof AuthenticatedLaboratoryIdRoute
  '/laboratory/new': typeof AuthenticatedLaboratoryNewRoute
  '/laboratory/tests': typeof AuthenticatedLaboratoryTestsRoute
  '/opd/$appointmentId': typeof AuthenticatedOpdAppointmentIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/pharmacy/medicines': typeof AuthenticatedPharmacyMedicinesRoute
  '/discharge/$id/print': typeof DischargeIdPrintRoute
  '/prescriptions/$id/print': typeof PrescriptionsIdPrintRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/ipd': typeof AuthenticatedIpdIndexRoute
  '/laboratory': typeof AuthenticatedLaboratoryIndexRoute
  '/pharmacy': typeof AuthenticatedPharmacyIndexRoute
  '/ipd/$id/discharge': typeof AuthenticatedIpdIdDischargeRoute
  '/pharmacy/sales/new': typeof AuthenticatedPharmacySalesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/ambulance': typeof AuthenticatedAmbulanceRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRouteWithChildren
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/health-packages': typeof AuthenticatedHealthPackagesRoute
  '/_authenticated/health-records': typeof AuthenticatedHealthRecordsRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/ipd': typeof AuthenticatedIpdRouteWithChildren
  '/_authenticated/laboratory': typeof AuthenticatedLaboratoryRouteWithChildren
  '/_authenticated/nurse-station': typeof AuthenticatedNurseStationRoute
  '/_authenticated/opd': typeof AuthenticatedOpdRouteWithChildren
  '/_authenticated/ot': typeof AuthenticatedOtRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/payments-online': typeof AuthenticatedPaymentsOnlineRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRouteWithChildren
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/_authenticated/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/billing/$id': typeof AuthenticatedBillingIdRoute
  '/_authenticated/billing/new': typeof AuthenticatedBillingNewRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/_authenticated/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/ipd/$id': typeof AuthenticatedIpdIdRouteWithChildren
  '/_authenticated/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/_authenticated/ipd/new': typeof AuthenticatedIpdNewRoute
  '/_authenticated/laboratory/$id': typeof AuthenticatedLaboratoryIdRoute
  '/_authenticated/laboratory/new': typeof AuthenticatedLaboratoryNewRoute
  '/_authenticated/laboratory/tests': typeof AuthenticatedLaboratoryTestsRoute
  '/_authenticated/opd/$appointmentId': typeof AuthenticatedOpdAppointmentIdRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/pharmacy/medicines': typeof AuthenticatedPharmacyMedicinesRoute
  '/discharge/$id/print': typeof DischargeIdPrintRoute
  '/prescriptions/$id/print': typeof PrescriptionsIdPrintRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/ipd/': typeof AuthenticatedIpdIndexRoute
  '/_authenticated/laboratory/': typeof AuthenticatedLaboratoryIndexRoute
  '/_authenticated/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
  '/_authenticated/ipd/$id/discharge': typeof AuthenticatedIpdIdDischargeRoute
  '/_authenticated/pharmacy/sales/new': typeof AuthenticatedPharmacySalesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-assistant'
    | '/ambulance'
    | '/appointments'
    | '/assets'
    | '/audit'
    | '/backups'
    | '/bi'
    | '/billing'
    | '/branches'
    | '/command-center'
    | '/communications'
    | '/crm'
    | '/dashboard'
    | '/emergency'
    | '/finance'
    | '/health-packages'
    | '/health-records'
    | '/insurance'
    | '/ipd'
    | '/laboratory'
    | '/nurse-station'
    | '/opd'
    | '/ot'
    | '/patients'
    | '/payments-online'
    | '/pharmacy'
    | '/procurement'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/telemedicine'
    | '/vaccinations'
    | '/vendors'
    | '/whatsapp'
    | '/billing/$id'
    | '/billing/new'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/ipd/$id'
    | '/ipd/beds'
    | '/ipd/new'
    | '/laboratory/$id'
    | '/laboratory/new'
    | '/laboratory/tests'
    | '/opd/$appointmentId'
    | '/patients/$id'
    | '/patients/new'
    | '/pharmacy/medicines'
    | '/discharge/$id/print'
    | '/prescriptions/$id/print'
    | '/billing/'
    | '/ipd/'
    | '/laboratory/'
    | '/pharmacy/'
    | '/ipd/$id/discharge'
    | '/pharmacy/sales/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-assistant'
    | '/ambulance'
    | '/appointments'
    | '/assets'
    | '/audit'
    | '/backups'
    | '/bi'
    | '/branches'
    | '/command-center'
    | '/communications'
    | '/crm'
    | '/dashboard'
    | '/emergency'
    | '/finance'
    | '/health-packages'
    | '/health-records'
    | '/insurance'
    | '/nurse-station'
    | '/opd'
    | '/ot'
    | '/patients'
    | '/payments-online'
    | '/procurement'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/telemedicine'
    | '/vaccinations'
    | '/vendors'
    | '/whatsapp'
    | '/billing/$id'
    | '/billing/new'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/ipd/$id'
    | '/ipd/beds'
    | '/ipd/new'
    | '/laboratory/$id'
    | '/laboratory/new'
    | '/laboratory/tests'
    | '/opd/$appointmentId'
    | '/patients/$id'
    | '/patients/new'
    | '/pharmacy/medicines'
    | '/discharge/$id/print'
    | '/prescriptions/$id/print'
    | '/billing'
    | '/ipd'
    | '/laboratory'
    | '/pharmacy'
    | '/ipd/$id/discharge'
    | '/pharmacy/sales/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/ambulance'
    | '/_authenticated/appointments'
    | '/_authenticated/assets'
    | '/_authenticated/audit'
    | '/_authenticated/backups'
    | '/_authenticated/bi'
    | '/_authenticated/billing'
    | '/_authenticated/branches'
    | '/_authenticated/command-center'
    | '/_authenticated/communications'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergency'
    | '/_authenticated/finance'
    | '/_authenticated/health-packages'
    | '/_authenticated/health-records'
    | '/_authenticated/insurance'
    | '/_authenticated/ipd'
    | '/_authenticated/laboratory'
    | '/_authenticated/nurse-station'
    | '/_authenticated/opd'
    | '/_authenticated/ot'
    | '/_authenticated/patients'
    | '/_authenticated/payments-online'
    | '/_authenticated/pharmacy'
    | '/_authenticated/procurement'
    | '/_authenticated/queue'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/telemedicine'
    | '/_authenticated/vaccinations'
    | '/_authenticated/vendors'
    | '/_authenticated/whatsapp'
    | '/_authenticated/billing/$id'
    | '/_authenticated/billing/new'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/employees'
    | '/_authenticated/hr/leave'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/ipd/$id'
    | '/_authenticated/ipd/beds'
    | '/_authenticated/ipd/new'
    | '/_authenticated/laboratory/$id'
    | '/_authenticated/laboratory/new'
    | '/_authenticated/laboratory/tests'
    | '/_authenticated/opd/$appointmentId'
    | '/_authenticated/patients/$id'
    | '/_authenticated/patients/new'
    | '/_authenticated/pharmacy/medicines'
    | '/discharge/$id/print'
    | '/prescriptions/$id/print'
    | '/_authenticated/billing/'
    | '/_authenticated/ipd/'
    | '/_authenticated/laboratory/'
    | '/_authenticated/pharmacy/'
    | '/_authenticated/ipd/$id/discharge'
    | '/_authenticated/pharmacy/sales/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  DischargeIdPrintRoute: typeof DischargeIdPrintRoute
  PrescriptionsIdPrintRoute: typeof PrescriptionsIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaccinations': {
      id: '/_authenticated/vaccinations'
      path: '/vaccinations'
      fullPath: '/vaccinations'
      preLoaderRoute: typeof AuthenticatedVaccinationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telemedicine': {
      id: '/_authenticated/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof AuthenticatedTelemedicineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments-online': {
      id: '/_authenticated/payments-online'
      path: '/payments-online'
      fullPath: '/payments-online'
      preLoaderRoute: typeof AuthenticatedPaymentsOnlineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ot': {
      id: '/_authenticated/ot'
      path: '/ot'
      fullPath: '/ot'
      preLoaderRoute: typeof AuthenticatedOtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd': {
      id: '/_authenticated/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof AuthenticatedOpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nurse-station': {
      id: '/_authenticated/nurse-station'
      path: '/nurse-station'
      fullPath: '/nurse-station'
      preLoaderRoute: typeof AuthenticatedNurseStationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laboratory': {
      id: '/_authenticated/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof AuthenticatedLaboratoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipd': {
      id: '/_authenticated/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof AuthenticatedIpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health-records': {
      id: '/_authenticated/health-records'
      path: '/health-records'
      fullPath: '/health-records'
      preLoaderRoute: typeof AuthenticatedHealthRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health-packages': {
      id: '/_authenticated/health-packages'
      path: '/health-packages'
      fullPath: '/health-packages'
      preLoaderRoute: typeof AuthenticatedHealthPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ambulance': {
      id: '/_authenticated/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AuthenticatedAmbulanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/': {
      id: '/_authenticated/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AuthenticatedPharmacyIndexRouteImport
      parentRoute: typeof AuthenticatedPharmacyRoute
    }
    '/_authenticated/laboratory/': {
      id: '/_authenticated/laboratory/'
      path: '/'
      fullPath: '/laboratory/'
      preLoaderRoute: typeof AuthenticatedLaboratoryIndexRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/ipd/': {
      id: '/_authenticated/ipd/'
      path: '/'
      fullPath: '/ipd/'
      preLoaderRoute: typeof AuthenticatedIpdIndexRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/prescriptions/$id/print': {
      id: '/prescriptions/$id/print'
      path: '/prescriptions/$id/print'
      fullPath: '/prescriptions/$id/print'
      preLoaderRoute: typeof PrescriptionsIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discharge/$id/print': {
      id: '/discharge/$id/print'
      path: '/discharge/$id/print'
      fullPath: '/discharge/$id/print'
      preLoaderRoute: typeof DischargeIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pharmacy/medicines': {
      id: '/_authenticated/pharmacy/medicines'
      path: '/medicines'
      fullPath: '/pharmacy/medicines'
      preLoaderRoute: typeof AuthenticatedPharmacyMedicinesRouteImport
      parentRoute: typeof AuthenticatedPharmacyRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/opd/$appointmentId': {
      id: '/_authenticated/opd/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/opd/$appointmentId'
      preLoaderRoute: typeof AuthenticatedOpdAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/laboratory/tests': {
      id: '/_authenticated/laboratory/tests'
      path: '/tests'
      fullPath: '/laboratory/tests'
      preLoaderRoute: typeof AuthenticatedLaboratoryTestsRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/laboratory/new': {
      id: '/_authenticated/laboratory/new'
      path: '/new'
      fullPath: '/laboratory/new'
      preLoaderRoute: typeof AuthenticatedLaboratoryNewRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/laboratory/$id': {
      id: '/_authenticated/laboratory/$id'
      path: '/$id'
      fullPath: '/laboratory/$id'
      preLoaderRoute: typeof AuthenticatedLaboratoryIdRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/ipd/new': {
      id: '/_authenticated/ipd/new'
      path: '/new'
      fullPath: '/ipd/new'
      preLoaderRoute: typeof AuthenticatedIpdNewRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/beds': {
      id: '/_authenticated/ipd/beds'
      path: '/beds'
      fullPath: '/ipd/beds'
      preLoaderRoute: typeof AuthenticatedIpdBedsRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/$id': {
      id: '/_authenticated/ipd/$id'
      path: '/$id'
      fullPath: '/ipd/$id'
      preLoaderRoute: typeof AuthenticatedIpdIdRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/leave': {
      id: '/_authenticated/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AuthenticatedHrLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/employees': {
      id: '/_authenticated/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthenticatedHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/new': {
      id: '/_authenticated/billing/new'
      path: '/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof AuthenticatedBillingNewRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/billing/$id': {
      id: '/_authenticated/billing/$id'
      path: '/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof AuthenticatedBillingIdRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/pharmacy/sales/new': {
      id: '/_authenticated/pharmacy/sales/new'
      path: '/sales/new'
      fullPath: '/pharmacy/sales/new'
      preLoaderRoute: typeof AuthenticatedPharmacySalesNewRouteImport
      parentRoute: typeof AuthenticatedPharmacyRoute
    }
    '/_authenticated/ipd/$id/discharge': {
      id: '/_authenticated/ipd/$id/discharge'
      path: '/discharge'
      fullPath: '/ipd/$id/discharge'
      preLoaderRoute: typeof AuthenticatedIpdIdDischargeRouteImport
      parentRoute: typeof AuthenticatedIpdIdRoute
    }
  }
}

interface AuthenticatedBillingRouteChildren {
  AuthenticatedBillingIdRoute: typeof AuthenticatedBillingIdRoute
  AuthenticatedBillingNewRoute: typeof AuthenticatedBillingNewRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
}

const AuthenticatedBillingRouteChildren: AuthenticatedBillingRouteChildren = {
  AuthenticatedBillingIdRoute: AuthenticatedBillingIdRoute,
  AuthenticatedBillingNewRoute: AuthenticatedBillingNewRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
}

const AuthenticatedBillingRouteWithChildren =
  AuthenticatedBillingRoute._addFileChildren(AuthenticatedBillingRouteChildren)

interface AuthenticatedIpdIdRouteChildren {
  AuthenticatedIpdIdDischargeRoute: typeof AuthenticatedIpdIdDischargeRoute
}

const AuthenticatedIpdIdRouteChildren: AuthenticatedIpdIdRouteChildren = {
  AuthenticatedIpdIdDischargeRoute: AuthenticatedIpdIdDischargeRoute,
}

const AuthenticatedIpdIdRouteWithChildren =
  AuthenticatedIpdIdRoute._addFileChildren(AuthenticatedIpdIdRouteChildren)

interface AuthenticatedIpdRouteChildren {
  AuthenticatedIpdIdRoute: typeof AuthenticatedIpdIdRouteWithChildren
  AuthenticatedIpdBedsRoute: typeof AuthenticatedIpdBedsRoute
  AuthenticatedIpdNewRoute: typeof AuthenticatedIpdNewRoute
  AuthenticatedIpdIndexRoute: typeof AuthenticatedIpdIndexRoute
}

const AuthenticatedIpdRouteChildren: AuthenticatedIpdRouteChildren = {
  AuthenticatedIpdIdRoute: AuthenticatedIpdIdRouteWithChildren,
  AuthenticatedIpdBedsRoute: AuthenticatedIpdBedsRoute,
  AuthenticatedIpdNewRoute: AuthenticatedIpdNewRoute,
  AuthenticatedIpdIndexRoute: AuthenticatedIpdIndexRoute,
}

const AuthenticatedIpdRouteWithChildren =
  AuthenticatedIpdRoute._addFileChildren(AuthenticatedIpdRouteChildren)

interface AuthenticatedLaboratoryRouteChildren {
  AuthenticatedLaboratoryIdRoute: typeof AuthenticatedLaboratoryIdRoute
  AuthenticatedLaboratoryNewRoute: typeof AuthenticatedLaboratoryNewRoute
  AuthenticatedLaboratoryTestsRoute: typeof AuthenticatedLaboratoryTestsRoute
  AuthenticatedLaboratoryIndexRoute: typeof AuthenticatedLaboratoryIndexRoute
}

const AuthenticatedLaboratoryRouteChildren: AuthenticatedLaboratoryRouteChildren =
  {
    AuthenticatedLaboratoryIdRoute: AuthenticatedLaboratoryIdRoute,
    AuthenticatedLaboratoryNewRoute: AuthenticatedLaboratoryNewRoute,
    AuthenticatedLaboratoryTestsRoute: AuthenticatedLaboratoryTestsRoute,
    AuthenticatedLaboratoryIndexRoute: AuthenticatedLaboratoryIndexRoute,
  }

const AuthenticatedLaboratoryRouteWithChildren =
  AuthenticatedLaboratoryRoute._addFileChildren(
    AuthenticatedLaboratoryRouteChildren,
  )

interface AuthenticatedOpdRouteChildren {
  AuthenticatedOpdAppointmentIdRoute: typeof AuthenticatedOpdAppointmentIdRoute
}

const AuthenticatedOpdRouteChildren: AuthenticatedOpdRouteChildren = {
  AuthenticatedOpdAppointmentIdRoute: AuthenticatedOpdAppointmentIdRoute,
}

const AuthenticatedOpdRouteWithChildren =
  AuthenticatedOpdRoute._addFileChildren(AuthenticatedOpdRouteChildren)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedPharmacyRouteChildren {
  AuthenticatedPharmacyMedicinesRoute: typeof AuthenticatedPharmacyMedicinesRoute
  AuthenticatedPharmacyIndexRoute: typeof AuthenticatedPharmacyIndexRoute
  AuthenticatedPharmacySalesNewRoute: typeof AuthenticatedPharmacySalesNewRoute
}

const AuthenticatedPharmacyRouteChildren: AuthenticatedPharmacyRouteChildren = {
  AuthenticatedPharmacyMedicinesRoute: AuthenticatedPharmacyMedicinesRoute,
  AuthenticatedPharmacyIndexRoute: AuthenticatedPharmacyIndexRoute,
  AuthenticatedPharmacySalesNewRoute: AuthenticatedPharmacySalesNewRoute,
}

const AuthenticatedPharmacyRouteWithChildren =
  AuthenticatedPharmacyRoute._addFileChildren(
    AuthenticatedPharmacyRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAmbulanceRoute: typeof AuthenticatedAmbulanceRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRouteWithChildren
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHealthPackagesRoute: typeof AuthenticatedHealthPackagesRoute
  AuthenticatedHealthRecordsRoute: typeof AuthenticatedHealthRecordsRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedIpdRoute: typeof AuthenticatedIpdRouteWithChildren
  AuthenticatedLaboratoryRoute: typeof AuthenticatedLaboratoryRouteWithChildren
  AuthenticatedNurseStationRoute: typeof AuthenticatedNurseStationRoute
  AuthenticatedOpdRoute: typeof AuthenticatedOpdRouteWithChildren
  AuthenticatedOtRoute: typeof AuthenticatedOtRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPaymentsOnlineRoute: typeof AuthenticatedPaymentsOnlineRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRouteWithChildren
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTelemedicineRoute: typeof AuthenticatedTelemedicineRoute
  AuthenticatedVaccinationsRoute: typeof AuthenticatedVaccinationsRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrEmployeesRoute: typeof AuthenticatedHrEmployeesRoute
  AuthenticatedHrLeaveRoute: typeof AuthenticatedHrLeaveRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAmbulanceRoute: AuthenticatedAmbulanceRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRouteWithChildren,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHealthPackagesRoute: AuthenticatedHealthPackagesRoute,
  AuthenticatedHealthRecordsRoute: AuthenticatedHealthRecordsRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedIpdRoute: AuthenticatedIpdRouteWithChildren,
  AuthenticatedLaboratoryRoute: AuthenticatedLaboratoryRouteWithChildren,
  AuthenticatedNurseStationRoute: AuthenticatedNurseStationRoute,
  AuthenticatedOpdRoute: AuthenticatedOpdRouteWithChildren,
  AuthenticatedOtRoute: AuthenticatedOtRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPaymentsOnlineRoute: AuthenticatedPaymentsOnlineRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRouteWithChildren,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTelemedicineRoute: AuthenticatedTelemedicineRoute,
  AuthenticatedVaccinationsRoute: AuthenticatedVaccinationsRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrEmployeesRoute: AuthenticatedHrEmployeesRoute,
  AuthenticatedHrLeaveRoute: AuthenticatedHrLeaveRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  DischargeIdPrintRoute: DischargeIdPrintRoute,
  PrescriptionsIdPrintRoute: PrescriptionsIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
