/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthCheckRouteImport } from './routes/health-check'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityCenterRouteImport } from './routes/_authenticated/security-center'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRadiologyRouteImport } from './routes/_authenticated/radiology'
import { Route as AuthenticatedQueueDisplayRouteImport } from './routes/_authenticated/queue-display'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPacsRouteImport } from './routes/_authenticated/pacs'
import { Route as AuthenticatedOtRouteImport } from './routes/_authenticated/ot'
import { Route as AuthenticatedOpdRouteImport } from './routes/_authenticated/opd'
import { Route as AuthenticatedNurseStationRouteImport } from './routes/_authenticated/nurse-station'
import { Route as AuthenticatedMobileApiRouteImport } from './routes/_authenticated/mobile-api'
import { Route as AuthenticatedLaboratoryRouteImport } from './routes/_authenticated/laboratory'
import { Route as AuthenticatedIpdRouteImport } from './routes/_authenticated/ipd'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedIcuRouteImport } from './routes/_authenticated/icu'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDischargeRouteImport } from './routes/_authenticated/discharge'
import { Route as AuthenticatedDialysisRouteImport } from './routes/_authenticated/dialysis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedBloodBankRouteImport } from './routes/_authenticated/blood-bank'
import { Route as AuthenticatedBiomedicalRouteImport } from './routes/_authenticated/biomedical'
import { Route as AuthenticatedBillingCenterRouteImport } from './routes/_authenticated/billing-center'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuthorityRouteImport } from './routes/_authenticated/authority'
import { Route as AuthenticatedAuditTrailRouteImport } from './routes/_authenticated/audit-trail'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedApiGatewayRouteImport } from './routes/_authenticated/api-gateway'
import { Route as AuthenticatedAmbulanceRouteImport } from './routes/_authenticated/ambulance'
import { Route as AuthenticatedPharmacyIndexRouteImport } from './routes/_authenticated/pharmacy.index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedOtIndexRouteImport } from './routes/_authenticated/ot.index'
import { Route as AuthenticatedLaboratoryIndexRouteImport } from './routes/_authenticated/laboratory.index'
import { Route as AuthenticatedIpdIndexRouteImport } from './routes/_authenticated/ipd.index'
import { Route as AuthenticatedIcuIndexRouteImport } from './routes/_authenticated/icu.index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing.index'
import { Route as PrescriptionsIdPrintRouteImport } from './routes/prescriptions.$id.print'
import { Route as PatientCardIdPrintRouteImport } from './routes/patient-card.$id.print'
import { Route as DischargeIdPrintRouteImport } from './routes/discharge.$id.print'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as AuthenticatedPharmacyMedicinesRouteImport } from './routes/_authenticated/pharmacy.medicines'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients.new'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedOtSettingsRouteImport } from './routes/_authenticated/ot.settings'
import { Route as AuthenticatedOtScheduleRouteImport } from './routes/_authenticated/ot.schedule'
import { Route as AuthenticatedOtReportsRouteImport } from './routes/_authenticated/ot.reports'
import { Route as AuthenticatedOtIdRouteImport } from './routes/_authenticated/ot.$id'
import { Route as AuthenticatedOpdSettingsRouteImport } from './routes/_authenticated/opd.settings'
import { Route as AuthenticatedOpdReportsRouteImport } from './routes/_authenticated/opd.reports'
import { Route as AuthenticatedOpdRegistrationRouteImport } from './routes/_authenticated/opd.registration'
import { Route as AuthenticatedOpdConsultationRouteImport } from './routes/_authenticated/opd.consultation'
import { Route as AuthenticatedOpdBillingRouteImport } from './routes/_authenticated/opd.billing'
import { Route as AuthenticatedOpdAppointmentsRouteImport } from './routes/_authenticated/opd.appointments'
import { Route as AuthenticatedOpdAppointmentIdRouteImport } from './routes/_authenticated/opd.$appointmentId'
import { Route as AuthenticatedLaboratoryTestsRouteImport } from './routes/_authenticated/laboratory.tests'
import { Route as AuthenticatedLaboratoryNewRouteImport } from './routes/_authenticated/laboratory.new'
import { Route as AuthenticatedLaboratoryIdRouteImport } from './routes/_authenticated/laboratory.$id'
import { Route as AuthenticatedIpdSettingsRouteImport } from './routes/_authenticated/ipd.settings'
import { Route as AuthenticatedIpdReportsRouteImport } from './routes/_authenticated/ipd.reports'
import { Route as AuthenticatedIpdNewRouteImport } from './routes/_authenticated/ipd.new'
import { Route as AuthenticatedIpdBirthRegisterRouteImport } from './routes/_authenticated/ipd.birth-register'
import { Route as AuthenticatedIpdBedsRouteImport } from './routes/_authenticated/ipd.beds'
import { Route as AuthenticatedIpdIdRouteImport } from './routes/_authenticated/ipd.$id'
import { Route as AuthenticatedIcuSettingsRouteImport } from './routes/_authenticated/icu.settings'
import { Route as AuthenticatedIcuReportsRouteImport } from './routes/_authenticated/icu.reports'
import { Route as AuthenticatedIcuIdRouteImport } from './routes/_authenticated/icu.$id'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr.payroll'
import { Route as AuthenticatedHrLeaveRouteImport } from './routes/_authenticated/hr.leave'
import { Route as AuthenticatedHrEmployeesRouteImport } from './routes/_authenticated/hr.employees'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr.attendance'
import { Route as AuthenticatedBillingReportsRouteImport } from './routes/_authenticated/billing.reports'
import { Route as AuthenticatedBillingPackagesRouteImport } from './routes/_authenticated/billing.packages'
import { Route as AuthenticatedBillingNewRouteImport } from './routes/_authenticated/billing.new'
import { Route as AuthenticatedBillingIdRouteImport } from './routes/_authenticated/billing.$id'
import { Route as AuthenticatedPharmacySalesNewRouteImport } from './routes/_authenticated/pharmacy.sales.new'
import { Route as AuthenticatedIpdIdDischargeRouteImport } from './routes/_authenticated/ipd.$id.discharge'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityCenterRoute =
  AuthenticatedSecurityCenterRouteImport.update({
    id: '/security-center',
    path: '/security-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRadiologyRoute = AuthenticatedRadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueueDisplayRoute =
  AuthenticatedQueueDisplayRouteImport.update({
    id: '/queue-display',
    path: '/queue-display',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacsRoute = AuthenticatedPacsRouteImport.update({
  id: '/pacs',
  path: '/pacs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOtRoute = AuthenticatedOtRouteImport.update({
  id: '/ot',
  path: '/ot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpdRoute = AuthenticatedOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNurseStationRoute =
  AuthenticatedNurseStationRouteImport.update({
    id: '/nurse-station',
    path: '/nurse-station',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMobileApiRoute = AuthenticatedMobileApiRouteImport.update({
  id: '/mobile-api',
  path: '/mobile-api',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLaboratoryRoute = AuthenticatedLaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpdRoute = AuthenticatedIpdRouteImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIcuRoute = AuthenticatedIcuRouteImport.update({
  id: '/icu',
  path: '/icu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDischargeRoute = AuthenticatedDischargeRouteImport.update({
  id: '/discharge',
  path: '/discharge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDialysisRoute = AuthenticatedDialysisRouteImport.update({
  id: '/dialysis',
  path: '/dialysis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBloodBankRoute = AuthenticatedBloodBankRouteImport.update({
  id: '/blood-bank',
  path: '/blood-bank',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiomedicalRoute = AuthenticatedBiomedicalRouteImport.update({
  id: '/biomedical',
  path: '/biomedical',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingCenterRoute =
  AuthenticatedBillingCenterRouteImport.update({
    id: '/billing-center',
    path: '/billing-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorityRoute = AuthenticatedAuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditTrailRoute = AuthenticatedAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiGatewayRoute = AuthenticatedApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAmbulanceRoute = AuthenticatedAmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPharmacyIndexRoute =
  AuthenticatedPharmacyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPharmacyRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedOtIndexRoute = AuthenticatedOtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOtRoute,
} as any)
const AuthenticatedLaboratoryIndexRoute =
  AuthenticatedLaboratoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedIpdIndexRoute = AuthenticatedIpdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIcuIndexRoute = AuthenticatedIcuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedIcuRoute,
} as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const PrescriptionsIdPrintRoute = PrescriptionsIdPrintRouteImport.update({
  id: '/prescriptions/$id/print',
  path: '/prescriptions/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientCardIdPrintRoute = PatientCardIdPrintRouteImport.update({
  id: '/patient-card/$id/print',
  path: '/patient-card/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const DischargeIdPrintRoute = DischargeIdPrintRouteImport.update({
  id: '/discharge/$id/print',
  path: '/discharge/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedPharmacyMedicinesRoute =
  AuthenticatedPharmacyMedicinesRouteImport.update({
    id: '/medicines',
    path: '/medicines',
    getParentRoute: () => AuthenticatedPharmacyRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPatientsRoute,
} as any)
const AuthenticatedOtSettingsRoute = AuthenticatedOtSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedOtRoute,
} as any)
const AuthenticatedOtScheduleRoute = AuthenticatedOtScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedOtRoute,
} as any)
const AuthenticatedOtReportsRoute = AuthenticatedOtReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedOtRoute,
} as any)
const AuthenticatedOtIdRoute = AuthenticatedOtIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOtRoute,
} as any)
const AuthenticatedOpdSettingsRoute =
  AuthenticatedOpdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOpdRoute,
  } as any)
const AuthenticatedOpdReportsRoute = AuthenticatedOpdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedOpdRoute,
} as any)
const AuthenticatedOpdRegistrationRoute =
  AuthenticatedOpdRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AuthenticatedOpdRoute,
  } as any)
const AuthenticatedOpdConsultationRoute =
  AuthenticatedOpdConsultationRouteImport.update({
    id: '/consultation',
    path: '/consultation',
    getParentRoute: () => AuthenticatedOpdRoute,
  } as any)
const AuthenticatedOpdBillingRoute = AuthenticatedOpdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedOpdRoute,
} as any)
const AuthenticatedOpdAppointmentsRoute =
  AuthenticatedOpdAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedOpdRoute,
  } as any)
const AuthenticatedOpdAppointmentIdRoute =
  AuthenticatedOpdAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AuthenticatedOpdRoute,
  } as any)
const AuthenticatedLaboratoryTestsRoute =
  AuthenticatedLaboratoryTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedLaboratoryNewRoute =
  AuthenticatedLaboratoryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedLaboratoryIdRoute =
  AuthenticatedLaboratoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLaboratoryRoute,
  } as any)
const AuthenticatedIpdSettingsRoute =
  AuthenticatedIpdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedIpdRoute,
  } as any)
const AuthenticatedIpdReportsRoute = AuthenticatedIpdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIpdNewRoute = AuthenticatedIpdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIpdBirthRegisterRoute =
  AuthenticatedIpdBirthRegisterRouteImport.update({
    id: '/birth-register',
    path: '/birth-register',
    getParentRoute: () => AuthenticatedIpdRoute,
  } as any)
const AuthenticatedIpdBedsRoute = AuthenticatedIpdBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIpdIdRoute = AuthenticatedIpdIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedIpdRoute,
} as any)
const AuthenticatedIcuSettingsRoute =
  AuthenticatedIcuSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedIcuRoute,
  } as any)
const AuthenticatedIcuReportsRoute = AuthenticatedIcuReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedIcuRoute,
} as any)
const AuthenticatedIcuIdRoute = AuthenticatedIcuIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedIcuRoute,
} as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrLeaveRoute = AuthenticatedHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrEmployeesRoute =
  AuthenticatedHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingReportsRoute =
  AuthenticatedBillingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const AuthenticatedBillingPackagesRoute =
  AuthenticatedBillingPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const AuthenticatedBillingNewRoute = AuthenticatedBillingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBillingRoute,
} as any)
const AuthenticatedBillingIdRoute = AuthenticatedBillingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBillingRoute,
} as any)
const AuthenticatedPharmacySalesNewRoute =
  AuthenticatedPharmacySalesNewRouteImport.update({
    id: '/sales/new',
    path: '/sales/new',
    getParentRoute: () => AuthenticatedPharmacyRoute,
  } as any)
const AuthenticatedIpdIdDischargeRoute =
  AuthenticatedIpdIdDischargeRouteImport.update({
    id: '/discharge',
    path: '/discharge',
    getParentRoute: () => AuthenticatedIpdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health-check': typeof HealthCheckRoute
  '/login': typeof LoginRoute
  '/ambulance': typeof AuthenticatedAmbulanceRoute
  '/api-gateway': typeof AuthenticatedApiGatewayRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/audit-trail': typeof AuthenticatedAuditTrailRoute
  '/authority': typeof AuthenticatedAuthorityRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/bi': typeof AuthenticatedBiRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/billing-center': typeof AuthenticatedBillingCenterRoute
  '/biomedical': typeof AuthenticatedBiomedicalRoute
  '/blood-bank': typeof AuthenticatedBloodBankRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dialysis': typeof AuthenticatedDialysisRoute
  '/discharge': typeof AuthenticatedDischargeRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/icu': typeof AuthenticatedIcuRouteWithChildren
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/ipd': typeof AuthenticatedIpdRouteWithChildren
  '/laboratory': typeof AuthenticatedLaboratoryRouteWithChildren
  '/mobile-api': typeof AuthenticatedMobileApiRoute
  '/nurse-station': typeof AuthenticatedNurseStationRoute
  '/opd': typeof AuthenticatedOpdRouteWithChildren
  '/ot': typeof AuthenticatedOtRouteWithChildren
  '/pacs': typeof AuthenticatedPacsRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/performance': typeof AuthenticatedPerformanceRoute
  '/pharmacy': typeof AuthenticatedPharmacyRouteWithChildren
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/queue-display': typeof AuthenticatedQueueDisplayRoute
  '/radiology': typeof AuthenticatedRadiologyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security-center': typeof AuthenticatedSecurityCenterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/vendors': typeof AuthenticatedVendorsRoute
  '/billing/$id': typeof AuthenticatedBillingIdRoute
  '/billing/new': typeof AuthenticatedBillingNewRoute
  '/billing/packages': typeof AuthenticatedBillingPackagesRoute
  '/billing/reports': typeof AuthenticatedBillingReportsRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/icu/$id': typeof AuthenticatedIcuIdRoute
  '/icu/reports': typeof AuthenticatedIcuReportsRoute
  '/icu/settings': typeof AuthenticatedIcuSettingsRoute
  '/ipd/$id': typeof AuthenticatedIpdIdRouteWithChildren
  '/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/ipd/birth-register': typeof AuthenticatedIpdBirthRegisterRoute
  '/ipd/new': typeof AuthenticatedIpdNewRoute
  '/ipd/reports': typeof AuthenticatedIpdReportsRoute
  '/ipd/settings': typeof AuthenticatedIpdSettingsRoute
  '/laboratory/$id': typeof AuthenticatedLaboratoryIdRoute
  '/laboratory/new': typeof AuthenticatedLaboratoryNewRoute
  '/laboratory/tests': typeof AuthenticatedLaboratoryTestsRoute
  '/opd/$appointmentId': typeof AuthenticatedOpdAppointmentIdRoute
  '/opd/appointments': typeof AuthenticatedOpdAppointmentsRoute
  '/opd/billing': typeof AuthenticatedOpdBillingRoute
  '/opd/consultation': typeof AuthenticatedOpdConsultationRoute
  '/opd/registration': typeof AuthenticatedOpdRegistrationRoute
  '/opd/reports': typeof AuthenticatedOpdReportsRoute
  '/opd/settings': typeof AuthenticatedOpdSettingsRoute
  '/ot/$id': typeof AuthenticatedOtIdRoute
  '/ot/reports': typeof AuthenticatedOtReportsRoute
  '/ot/schedule': typeof AuthenticatedOtScheduleRoute
  '/ot/settings': typeof AuthenticatedOtSettingsRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/pharmacy/medicines': typeof AuthenticatedPharmacyMedicinesRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/discharge/$id/print': typeof DischargeIdPrintRoute
  '/patient-card/$id/print': typeof PatientCardIdPrintRoute
  '/prescriptions/$id/print': typeof PrescriptionsIdPrintRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/icu/': typeof AuthenticatedIcuIndexRoute
  '/ipd/': typeof AuthenticatedIpdIndexRoute
  '/laboratory/': typeof AuthenticatedLaboratoryIndexRoute
  '/ot/': typeof AuthenticatedOtIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
  '/ipd/$id/discharge': typeof AuthenticatedIpdIdDischargeRoute
  '/pharmacy/sales/new': typeof AuthenticatedPharmacySalesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health-check': typeof HealthCheckRoute
  '/login': typeof LoginRoute
  '/ambulance': typeof AuthenticatedAmbulanceRoute
  '/api-gateway': typeof AuthenticatedApiGatewayRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/audit-trail': typeof AuthenticatedAuditTrailRoute
  '/authority': typeof AuthenticatedAuthorityRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/bi': typeof AuthenticatedBiRoute
  '/billing-center': typeof AuthenticatedBillingCenterRoute
  '/biomedical': typeof AuthenticatedBiomedicalRoute
  '/blood-bank': typeof AuthenticatedBloodBankRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dialysis': typeof AuthenticatedDialysisRoute
  '/discharge': typeof AuthenticatedDischargeRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/mobile-api': typeof AuthenticatedMobileApiRoute
  '/nurse-station': typeof AuthenticatedNurseStationRoute
  '/opd': typeof AuthenticatedOpdRouteWithChildren
  '/pacs': typeof AuthenticatedPacsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/queue-display': typeof AuthenticatedQueueDisplayRoute
  '/radiology': typeof AuthenticatedRadiologyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security-center': typeof AuthenticatedSecurityCenterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/vendors': typeof AuthenticatedVendorsRoute
  '/billing/$id': typeof AuthenticatedBillingIdRoute
  '/billing/new': typeof AuthenticatedBillingNewRoute
  '/billing/packages': typeof AuthenticatedBillingPackagesRoute
  '/billing/reports': typeof AuthenticatedBillingReportsRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/icu/$id': typeof AuthenticatedIcuIdRoute
  '/icu/reports': typeof AuthenticatedIcuReportsRoute
  '/icu/settings': typeof AuthenticatedIcuSettingsRoute
  '/ipd/$id': typeof AuthenticatedIpdIdRouteWithChildren
  '/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/ipd/birth-register': typeof AuthenticatedIpdBirthRegisterRoute
  '/ipd/new': typeof AuthenticatedIpdNewRoute
  '/ipd/reports': typeof AuthenticatedIpdReportsRoute
  '/ipd/settings': typeof AuthenticatedIpdSettingsRoute
  '/laboratory/$id': typeof AuthenticatedLaboratoryIdRoute
  '/laboratory/new': typeof AuthenticatedLaboratoryNewRoute
  '/laboratory/tests': typeof AuthenticatedLaboratoryTestsRoute
  '/opd/$appointmentId': typeof AuthenticatedOpdAppointmentIdRoute
  '/opd/appointments': typeof AuthenticatedOpdAppointmentsRoute
  '/opd/billing': typeof AuthenticatedOpdBillingRoute
  '/opd/consultation': typeof AuthenticatedOpdConsultationRoute
  '/opd/registration': typeof AuthenticatedOpdRegistrationRoute
  '/opd/reports': typeof AuthenticatedOpdReportsRoute
  '/opd/settings': typeof AuthenticatedOpdSettingsRoute
  '/ot/$id': typeof AuthenticatedOtIdRoute
  '/ot/reports': typeof AuthenticatedOtReportsRoute
  '/ot/schedule': typeof AuthenticatedOtScheduleRoute
  '/ot/settings': typeof AuthenticatedOtSettingsRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/pharmacy/medicines': typeof AuthenticatedPharmacyMedicinesRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/discharge/$id/print': typeof DischargeIdPrintRoute
  '/patient-card/$id/print': typeof PatientCardIdPrintRoute
  '/prescriptions/$id/print': typeof PrescriptionsIdPrintRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/icu': typeof AuthenticatedIcuIndexRoute
  '/ipd': typeof AuthenticatedIpdIndexRoute
  '/laboratory': typeof AuthenticatedLaboratoryIndexRoute
  '/ot': typeof AuthenticatedOtIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/pharmacy': typeof AuthenticatedPharmacyIndexRoute
  '/ipd/$id/discharge': typeof AuthenticatedIpdIdDischargeRoute
  '/pharmacy/sales/new': typeof AuthenticatedPharmacySalesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/health-check': typeof HealthCheckRoute
  '/login': typeof LoginRoute
  '/_authenticated/ambulance': typeof AuthenticatedAmbulanceRoute
  '/_authenticated/api-gateway': typeof AuthenticatedApiGatewayRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/audit-trail': typeof AuthenticatedAuditTrailRoute
  '/_authenticated/authority': typeof AuthenticatedAuthorityRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRouteWithChildren
  '/_authenticated/billing-center': typeof AuthenticatedBillingCenterRoute
  '/_authenticated/biomedical': typeof AuthenticatedBiomedicalRoute
  '/_authenticated/blood-bank': typeof AuthenticatedBloodBankRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dialysis': typeof AuthenticatedDialysisRoute
  '/_authenticated/discharge': typeof AuthenticatedDischargeRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/icu': typeof AuthenticatedIcuRouteWithChildren
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/ipd': typeof AuthenticatedIpdRouteWithChildren
  '/_authenticated/laboratory': typeof AuthenticatedLaboratoryRouteWithChildren
  '/_authenticated/mobile-api': typeof AuthenticatedMobileApiRoute
  '/_authenticated/nurse-station': typeof AuthenticatedNurseStationRoute
  '/_authenticated/opd': typeof AuthenticatedOpdRouteWithChildren
  '/_authenticated/ot': typeof AuthenticatedOtRouteWithChildren
  '/_authenticated/pacs': typeof AuthenticatedPacsRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRouteWithChildren
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/queue-display': typeof AuthenticatedQueueDisplayRoute
  '/_authenticated/radiology': typeof AuthenticatedRadiologyRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security-center': typeof AuthenticatedSecurityCenterRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/billing/$id': typeof AuthenticatedBillingIdRoute
  '/_authenticated/billing/new': typeof AuthenticatedBillingNewRoute
  '/_authenticated/billing/packages': typeof AuthenticatedBillingPackagesRoute
  '/_authenticated/billing/reports': typeof AuthenticatedBillingReportsRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/_authenticated/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/icu/$id': typeof AuthenticatedIcuIdRoute
  '/_authenticated/icu/reports': typeof AuthenticatedIcuReportsRoute
  '/_authenticated/icu/settings': typeof AuthenticatedIcuSettingsRoute
  '/_authenticated/ipd/$id': typeof AuthenticatedIpdIdRouteWithChildren
  '/_authenticated/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/_authenticated/ipd/birth-register': typeof AuthenticatedIpdBirthRegisterRoute
  '/_authenticated/ipd/new': typeof AuthenticatedIpdNewRoute
  '/_authenticated/ipd/reports': typeof AuthenticatedIpdReportsRoute
  '/_authenticated/ipd/settings': typeof AuthenticatedIpdSettingsRoute
  '/_authenticated/laboratory/$id': typeof AuthenticatedLaboratoryIdRoute
  '/_authenticated/laboratory/new': typeof AuthenticatedLaboratoryNewRoute
  '/_authenticated/laboratory/tests': typeof AuthenticatedLaboratoryTestsRoute
  '/_authenticated/opd/$appointmentId': typeof AuthenticatedOpdAppointmentIdRoute
  '/_authenticated/opd/appointments': typeof AuthenticatedOpdAppointmentsRoute
  '/_authenticated/opd/billing': typeof AuthenticatedOpdBillingRoute
  '/_authenticated/opd/consultation': typeof AuthenticatedOpdConsultationRoute
  '/_authenticated/opd/registration': typeof AuthenticatedOpdRegistrationRoute
  '/_authenticated/opd/reports': typeof AuthenticatedOpdReportsRoute
  '/_authenticated/opd/settings': typeof AuthenticatedOpdSettingsRoute
  '/_authenticated/ot/$id': typeof AuthenticatedOtIdRoute
  '/_authenticated/ot/reports': typeof AuthenticatedOtReportsRoute
  '/_authenticated/ot/schedule': typeof AuthenticatedOtScheduleRoute
  '/_authenticated/ot/settings': typeof AuthenticatedOtSettingsRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/pharmacy/medicines': typeof AuthenticatedPharmacyMedicinesRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/discharge/$id/print': typeof DischargeIdPrintRoute
  '/patient-card/$id/print': typeof PatientCardIdPrintRoute
  '/prescriptions/$id/print': typeof PrescriptionsIdPrintRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/icu/': typeof AuthenticatedIcuIndexRoute
  '/_authenticated/ipd/': typeof AuthenticatedIpdIndexRoute
  '/_authenticated/laboratory/': typeof AuthenticatedLaboratoryIndexRoute
  '/_authenticated/ot/': typeof AuthenticatedOtIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
  '/_authenticated/ipd/$id/discharge': typeof AuthenticatedIpdIdDischargeRoute
  '/_authenticated/pharmacy/sales/new': typeof AuthenticatedPharmacySalesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health-check'
    | '/login'
    | '/ambulance'
    | '/api-gateway'
    | '/appointments'
    | '/assets'
    | '/audit'
    | '/audit-trail'
    | '/authority'
    | '/backups'
    | '/bi'
    | '/billing'
    | '/billing-center'
    | '/biomedical'
    | '/blood-bank'
    | '/branches'
    | '/change-password'
    | '/dashboard'
    | '/dialysis'
    | '/discharge'
    | '/documents'
    | '/emergency'
    | '/finance'
    | '/icu'
    | '/insurance'
    | '/ipd'
    | '/laboratory'
    | '/mobile-api'
    | '/nurse-station'
    | '/opd'
    | '/ot'
    | '/pacs'
    | '/patients'
    | '/performance'
    | '/pharmacy'
    | '/procurement'
    | '/queue'
    | '/queue-display'
    | '/radiology'
    | '/reports'
    | '/security-center'
    | '/settings'
    | '/staff'
    | '/vendors'
    | '/billing/$id'
    | '/billing/new'
    | '/billing/packages'
    | '/billing/reports'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/icu/$id'
    | '/icu/reports'
    | '/icu/settings'
    | '/ipd/$id'
    | '/ipd/beds'
    | '/ipd/birth-register'
    | '/ipd/new'
    | '/ipd/reports'
    | '/ipd/settings'
    | '/laboratory/$id'
    | '/laboratory/new'
    | '/laboratory/tests'
    | '/opd/$appointmentId'
    | '/opd/appointments'
    | '/opd/billing'
    | '/opd/consultation'
    | '/opd/registration'
    | '/opd/reports'
    | '/opd/settings'
    | '/ot/$id'
    | '/ot/reports'
    | '/ot/schedule'
    | '/ot/settings'
    | '/patients/$id'
    | '/patients/new'
    | '/pharmacy/medicines'
    | '/staff/$id'
    | '/discharge/$id/print'
    | '/patient-card/$id/print'
    | '/prescriptions/$id/print'
    | '/billing/'
    | '/icu/'
    | '/ipd/'
    | '/laboratory/'
    | '/ot/'
    | '/patients/'
    | '/pharmacy/'
    | '/ipd/$id/discharge'
    | '/pharmacy/sales/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health-check'
    | '/login'
    | '/ambulance'
    | '/api-gateway'
    | '/appointments'
    | '/assets'
    | '/audit'
    | '/audit-trail'
    | '/authority'
    | '/backups'
    | '/bi'
    | '/billing-center'
    | '/biomedical'
    | '/blood-bank'
    | '/branches'
    | '/change-password'
    | '/dashboard'
    | '/dialysis'
    | '/discharge'
    | '/documents'
    | '/emergency'
    | '/finance'
    | '/insurance'
    | '/mobile-api'
    | '/nurse-station'
    | '/opd'
    | '/pacs'
    | '/performance'
    | '/procurement'
    | '/queue'
    | '/queue-display'
    | '/radiology'
    | '/reports'
    | '/security-center'
    | '/settings'
    | '/staff'
    | '/vendors'
    | '/billing/$id'
    | '/billing/new'
    | '/billing/packages'
    | '/billing/reports'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/leave'
    | '/hr/payroll'
    | '/icu/$id'
    | '/icu/reports'
    | '/icu/settings'
    | '/ipd/$id'
    | '/ipd/beds'
    | '/ipd/birth-register'
    | '/ipd/new'
    | '/ipd/reports'
    | '/ipd/settings'
    | '/laboratory/$id'
    | '/laboratory/new'
    | '/laboratory/tests'
    | '/opd/$appointmentId'
    | '/opd/appointments'
    | '/opd/billing'
    | '/opd/consultation'
    | '/opd/registration'
    | '/opd/reports'
    | '/opd/settings'
    | '/ot/$id'
    | '/ot/reports'
    | '/ot/schedule'
    | '/ot/settings'
    | '/patients/$id'
    | '/patients/new'
    | '/pharmacy/medicines'
    | '/staff/$id'
    | '/discharge/$id/print'
    | '/patient-card/$id/print'
    | '/prescriptions/$id/print'
    | '/billing'
    | '/icu'
    | '/ipd'
    | '/laboratory'
    | '/ot'
    | '/patients'
    | '/pharmacy'
    | '/ipd/$id/discharge'
    | '/pharmacy/sales/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/health-check'
    | '/login'
    | '/_authenticated/ambulance'
    | '/_authenticated/api-gateway'
    | '/_authenticated/appointments'
    | '/_authenticated/assets'
    | '/_authenticated/audit'
    | '/_authenticated/audit-trail'
    | '/_authenticated/authority'
    | '/_authenticated/backups'
    | '/_authenticated/bi'
    | '/_authenticated/billing'
    | '/_authenticated/billing-center'
    | '/_authenticated/biomedical'
    | '/_authenticated/blood-bank'
    | '/_authenticated/branches'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/dialysis'
    | '/_authenticated/discharge'
    | '/_authenticated/documents'
    | '/_authenticated/emergency'
    | '/_authenticated/finance'
    | '/_authenticated/icu'
    | '/_authenticated/insurance'
    | '/_authenticated/ipd'
    | '/_authenticated/laboratory'
    | '/_authenticated/mobile-api'
    | '/_authenticated/nurse-station'
    | '/_authenticated/opd'
    | '/_authenticated/ot'
    | '/_authenticated/pacs'
    | '/_authenticated/patients'
    | '/_authenticated/performance'
    | '/_authenticated/pharmacy'
    | '/_authenticated/procurement'
    | '/_authenticated/queue'
    | '/_authenticated/queue-display'
    | '/_authenticated/radiology'
    | '/_authenticated/reports'
    | '/_authenticated/security-center'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/vendors'
    | '/_authenticated/billing/$id'
    | '/_authenticated/billing/new'
    | '/_authenticated/billing/packages'
    | '/_authenticated/billing/reports'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/employees'
    | '/_authenticated/hr/leave'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/icu/$id'
    | '/_authenticated/icu/reports'
    | '/_authenticated/icu/settings'
    | '/_authenticated/ipd/$id'
    | '/_authenticated/ipd/beds'
    | '/_authenticated/ipd/birth-register'
    | '/_authenticated/ipd/new'
    | '/_authenticated/ipd/reports'
    | '/_authenticated/ipd/settings'
    | '/_authenticated/laboratory/$id'
    | '/_authenticated/laboratory/new'
    | '/_authenticated/laboratory/tests'
    | '/_authenticated/opd/$appointmentId'
    | '/_authenticated/opd/appointments'
    | '/_authenticated/opd/billing'
    | '/_authenticated/opd/consultation'
    | '/_authenticated/opd/registration'
    | '/_authenticated/opd/reports'
    | '/_authenticated/opd/settings'
    | '/_authenticated/ot/$id'
    | '/_authenticated/ot/reports'
    | '/_authenticated/ot/schedule'
    | '/_authenticated/ot/settings'
    | '/_authenticated/patients/$id'
    | '/_authenticated/patients/new'
    | '/_authenticated/pharmacy/medicines'
    | '/_authenticated/staff/$id'
    | '/discharge/$id/print'
    | '/patient-card/$id/print'
    | '/prescriptions/$id/print'
    | '/_authenticated/billing/'
    | '/_authenticated/icu/'
    | '/_authenticated/ipd/'
    | '/_authenticated/laboratory/'
    | '/_authenticated/ot/'
    | '/_authenticated/patients/'
    | '/_authenticated/pharmacy/'
    | '/_authenticated/ipd/$id/discharge'
    | '/_authenticated/pharmacy/sales/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthCheckRoute: typeof HealthCheckRoute
  LoginRoute: typeof LoginRoute
  DischargeIdPrintRoute: typeof DischargeIdPrintRoute
  PatientCardIdPrintRoute: typeof PatientCardIdPrintRoute
  PrescriptionsIdPrintRoute: typeof PrescriptionsIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security-center': {
      id: '/_authenticated/security-center'
      path: '/security-center'
      fullPath: '/security-center'
      preLoaderRoute: typeof AuthenticatedSecurityCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radiology': {
      id: '/_authenticated/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof AuthenticatedRadiologyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue-display': {
      id: '/_authenticated/queue-display'
      path: '/queue-display'
      fullPath: '/queue-display'
      preLoaderRoute: typeof AuthenticatedQueueDisplayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacs': {
      id: '/_authenticated/pacs'
      path: '/pacs'
      fullPath: '/pacs'
      preLoaderRoute: typeof AuthenticatedPacsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ot': {
      id: '/_authenticated/ot'
      path: '/ot'
      fullPath: '/ot'
      preLoaderRoute: typeof AuthenticatedOtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd': {
      id: '/_authenticated/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof AuthenticatedOpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nurse-station': {
      id: '/_authenticated/nurse-station'
      path: '/nurse-station'
      fullPath: '/nurse-station'
      preLoaderRoute: typeof AuthenticatedNurseStationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile-api': {
      id: '/_authenticated/mobile-api'
      path: '/mobile-api'
      fullPath: '/mobile-api'
      preLoaderRoute: typeof AuthenticatedMobileApiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laboratory': {
      id: '/_authenticated/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof AuthenticatedLaboratoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipd': {
      id: '/_authenticated/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof AuthenticatedIpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/icu': {
      id: '/_authenticated/icu'
      path: '/icu'
      fullPath: '/icu'
      preLoaderRoute: typeof AuthenticatedIcuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discharge': {
      id: '/_authenticated/discharge'
      path: '/discharge'
      fullPath: '/discharge'
      preLoaderRoute: typeof AuthenticatedDischargeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dialysis': {
      id: '/_authenticated/dialysis'
      path: '/dialysis'
      fullPath: '/dialysis'
      preLoaderRoute: typeof AuthenticatedDialysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blood-bank': {
      id: '/_authenticated/blood-bank'
      path: '/blood-bank'
      fullPath: '/blood-bank'
      preLoaderRoute: typeof AuthenticatedBloodBankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biomedical': {
      id: '/_authenticated/biomedical'
      path: '/biomedical'
      fullPath: '/biomedical'
      preLoaderRoute: typeof AuthenticatedBiomedicalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing-center': {
      id: '/_authenticated/billing-center'
      path: '/billing-center'
      fullPath: '/billing-center'
      preLoaderRoute: typeof AuthenticatedBillingCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authority': {
      id: '/_authenticated/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthenticatedAuthorityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-trail': {
      id: '/_authenticated/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuthenticatedAuditTrailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-gateway': {
      id: '/_authenticated/api-gateway'
      path: '/api-gateway'
      fullPath: '/api-gateway'
      preLoaderRoute: typeof AuthenticatedApiGatewayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ambulance': {
      id: '/_authenticated/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AuthenticatedAmbulanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/': {
      id: '/_authenticated/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AuthenticatedPharmacyIndexRouteImport
      parentRoute: typeof AuthenticatedPharmacyRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/ot/': {
      id: '/_authenticated/ot/'
      path: '/'
      fullPath: '/ot/'
      preLoaderRoute: typeof AuthenticatedOtIndexRouteImport
      parentRoute: typeof AuthenticatedOtRoute
    }
    '/_authenticated/laboratory/': {
      id: '/_authenticated/laboratory/'
      path: '/'
      fullPath: '/laboratory/'
      preLoaderRoute: typeof AuthenticatedLaboratoryIndexRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/ipd/': {
      id: '/_authenticated/ipd/'
      path: '/'
      fullPath: '/ipd/'
      preLoaderRoute: typeof AuthenticatedIpdIndexRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/icu/': {
      id: '/_authenticated/icu/'
      path: '/'
      fullPath: '/icu/'
      preLoaderRoute: typeof AuthenticatedIcuIndexRouteImport
      parentRoute: typeof AuthenticatedIcuRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/prescriptions/$id/print': {
      id: '/prescriptions/$id/print'
      path: '/prescriptions/$id/print'
      fullPath: '/prescriptions/$id/print'
      preLoaderRoute: typeof PrescriptionsIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-card/$id/print': {
      id: '/patient-card/$id/print'
      path: '/patient-card/$id/print'
      fullPath: '/patient-card/$id/print'
      preLoaderRoute: typeof PatientCardIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discharge/$id/print': {
      id: '/discharge/$id/print'
      path: '/discharge/$id/print'
      fullPath: '/discharge/$id/print'
      preLoaderRoute: typeof DischargeIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/pharmacy/medicines': {
      id: '/_authenticated/pharmacy/medicines'
      path: '/medicines'
      fullPath: '/pharmacy/medicines'
      preLoaderRoute: typeof AuthenticatedPharmacyMedicinesRouteImport
      parentRoute: typeof AuthenticatedPharmacyRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/ot/settings': {
      id: '/_authenticated/ot/settings'
      path: '/settings'
      fullPath: '/ot/settings'
      preLoaderRoute: typeof AuthenticatedOtSettingsRouteImport
      parentRoute: typeof AuthenticatedOtRoute
    }
    '/_authenticated/ot/schedule': {
      id: '/_authenticated/ot/schedule'
      path: '/schedule'
      fullPath: '/ot/schedule'
      preLoaderRoute: typeof AuthenticatedOtScheduleRouteImport
      parentRoute: typeof AuthenticatedOtRoute
    }
    '/_authenticated/ot/reports': {
      id: '/_authenticated/ot/reports'
      path: '/reports'
      fullPath: '/ot/reports'
      preLoaderRoute: typeof AuthenticatedOtReportsRouteImport
      parentRoute: typeof AuthenticatedOtRoute
    }
    '/_authenticated/ot/$id': {
      id: '/_authenticated/ot/$id'
      path: '/$id'
      fullPath: '/ot/$id'
      preLoaderRoute: typeof AuthenticatedOtIdRouteImport
      parentRoute: typeof AuthenticatedOtRoute
    }
    '/_authenticated/opd/settings': {
      id: '/_authenticated/opd/settings'
      path: '/settings'
      fullPath: '/opd/settings'
      preLoaderRoute: typeof AuthenticatedOpdSettingsRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/opd/reports': {
      id: '/_authenticated/opd/reports'
      path: '/reports'
      fullPath: '/opd/reports'
      preLoaderRoute: typeof AuthenticatedOpdReportsRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/opd/registration': {
      id: '/_authenticated/opd/registration'
      path: '/registration'
      fullPath: '/opd/registration'
      preLoaderRoute: typeof AuthenticatedOpdRegistrationRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/opd/consultation': {
      id: '/_authenticated/opd/consultation'
      path: '/consultation'
      fullPath: '/opd/consultation'
      preLoaderRoute: typeof AuthenticatedOpdConsultationRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/opd/billing': {
      id: '/_authenticated/opd/billing'
      path: '/billing'
      fullPath: '/opd/billing'
      preLoaderRoute: typeof AuthenticatedOpdBillingRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/opd/appointments': {
      id: '/_authenticated/opd/appointments'
      path: '/appointments'
      fullPath: '/opd/appointments'
      preLoaderRoute: typeof AuthenticatedOpdAppointmentsRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/opd/$appointmentId': {
      id: '/_authenticated/opd/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/opd/$appointmentId'
      preLoaderRoute: typeof AuthenticatedOpdAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedOpdRoute
    }
    '/_authenticated/laboratory/tests': {
      id: '/_authenticated/laboratory/tests'
      path: '/tests'
      fullPath: '/laboratory/tests'
      preLoaderRoute: typeof AuthenticatedLaboratoryTestsRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/laboratory/new': {
      id: '/_authenticated/laboratory/new'
      path: '/new'
      fullPath: '/laboratory/new'
      preLoaderRoute: typeof AuthenticatedLaboratoryNewRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/laboratory/$id': {
      id: '/_authenticated/laboratory/$id'
      path: '/$id'
      fullPath: '/laboratory/$id'
      preLoaderRoute: typeof AuthenticatedLaboratoryIdRouteImport
      parentRoute: typeof AuthenticatedLaboratoryRoute
    }
    '/_authenticated/ipd/settings': {
      id: '/_authenticated/ipd/settings'
      path: '/settings'
      fullPath: '/ipd/settings'
      preLoaderRoute: typeof AuthenticatedIpdSettingsRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/reports': {
      id: '/_authenticated/ipd/reports'
      path: '/reports'
      fullPath: '/ipd/reports'
      preLoaderRoute: typeof AuthenticatedIpdReportsRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/new': {
      id: '/_authenticated/ipd/new'
      path: '/new'
      fullPath: '/ipd/new'
      preLoaderRoute: typeof AuthenticatedIpdNewRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/birth-register': {
      id: '/_authenticated/ipd/birth-register'
      path: '/birth-register'
      fullPath: '/ipd/birth-register'
      preLoaderRoute: typeof AuthenticatedIpdBirthRegisterRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/beds': {
      id: '/_authenticated/ipd/beds'
      path: '/beds'
      fullPath: '/ipd/beds'
      preLoaderRoute: typeof AuthenticatedIpdBedsRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/ipd/$id': {
      id: '/_authenticated/ipd/$id'
      path: '/$id'
      fullPath: '/ipd/$id'
      preLoaderRoute: typeof AuthenticatedIpdIdRouteImport
      parentRoute: typeof AuthenticatedIpdRoute
    }
    '/_authenticated/icu/settings': {
      id: '/_authenticated/icu/settings'
      path: '/settings'
      fullPath: '/icu/settings'
      preLoaderRoute: typeof AuthenticatedIcuSettingsRouteImport
      parentRoute: typeof AuthenticatedIcuRoute
    }
    '/_authenticated/icu/reports': {
      id: '/_authenticated/icu/reports'
      path: '/reports'
      fullPath: '/icu/reports'
      preLoaderRoute: typeof AuthenticatedIcuReportsRouteImport
      parentRoute: typeof AuthenticatedIcuRoute
    }
    '/_authenticated/icu/$id': {
      id: '/_authenticated/icu/$id'
      path: '/$id'
      fullPath: '/icu/$id'
      preLoaderRoute: typeof AuthenticatedIcuIdRouteImport
      parentRoute: typeof AuthenticatedIcuRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/leave': {
      id: '/_authenticated/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AuthenticatedHrLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/employees': {
      id: '/_authenticated/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthenticatedHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/reports': {
      id: '/_authenticated/billing/reports'
      path: '/reports'
      fullPath: '/billing/reports'
      preLoaderRoute: typeof AuthenticatedBillingReportsRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/billing/packages': {
      id: '/_authenticated/billing/packages'
      path: '/packages'
      fullPath: '/billing/packages'
      preLoaderRoute: typeof AuthenticatedBillingPackagesRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/billing/new': {
      id: '/_authenticated/billing/new'
      path: '/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof AuthenticatedBillingNewRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/billing/$id': {
      id: '/_authenticated/billing/$id'
      path: '/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof AuthenticatedBillingIdRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/pharmacy/sales/new': {
      id: '/_authenticated/pharmacy/sales/new'
      path: '/sales/new'
      fullPath: '/pharmacy/sales/new'
      preLoaderRoute: typeof AuthenticatedPharmacySalesNewRouteImport
      parentRoute: typeof AuthenticatedPharmacyRoute
    }
    '/_authenticated/ipd/$id/discharge': {
      id: '/_authenticated/ipd/$id/discharge'
      path: '/discharge'
      fullPath: '/ipd/$id/discharge'
      preLoaderRoute: typeof AuthenticatedIpdIdDischargeRouteImport
      parentRoute: typeof AuthenticatedIpdIdRoute
    }
  }
}

interface AuthenticatedBillingRouteChildren {
  AuthenticatedBillingIdRoute: typeof AuthenticatedBillingIdRoute
  AuthenticatedBillingNewRoute: typeof AuthenticatedBillingNewRoute
  AuthenticatedBillingPackagesRoute: typeof AuthenticatedBillingPackagesRoute
  AuthenticatedBillingReportsRoute: typeof AuthenticatedBillingReportsRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
}

const AuthenticatedBillingRouteChildren: AuthenticatedBillingRouteChildren = {
  AuthenticatedBillingIdRoute: AuthenticatedBillingIdRoute,
  AuthenticatedBillingNewRoute: AuthenticatedBillingNewRoute,
  AuthenticatedBillingPackagesRoute: AuthenticatedBillingPackagesRoute,
  AuthenticatedBillingReportsRoute: AuthenticatedBillingReportsRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
}

const AuthenticatedBillingRouteWithChildren =
  AuthenticatedBillingRoute._addFileChildren(AuthenticatedBillingRouteChildren)

interface AuthenticatedIcuRouteChildren {
  AuthenticatedIcuIdRoute: typeof AuthenticatedIcuIdRoute
  AuthenticatedIcuReportsRoute: typeof AuthenticatedIcuReportsRoute
  AuthenticatedIcuSettingsRoute: typeof AuthenticatedIcuSettingsRoute
  AuthenticatedIcuIndexRoute: typeof AuthenticatedIcuIndexRoute
}

const AuthenticatedIcuRouteChildren: AuthenticatedIcuRouteChildren = {
  AuthenticatedIcuIdRoute: AuthenticatedIcuIdRoute,
  AuthenticatedIcuReportsRoute: AuthenticatedIcuReportsRoute,
  AuthenticatedIcuSettingsRoute: AuthenticatedIcuSettingsRoute,
  AuthenticatedIcuIndexRoute: AuthenticatedIcuIndexRoute,
}

const AuthenticatedIcuRouteWithChildren =
  AuthenticatedIcuRoute._addFileChildren(AuthenticatedIcuRouteChildren)

interface AuthenticatedIpdIdRouteChildren {
  AuthenticatedIpdIdDischargeRoute: typeof AuthenticatedIpdIdDischargeRoute
}

const AuthenticatedIpdIdRouteChildren: AuthenticatedIpdIdRouteChildren = {
  AuthenticatedIpdIdDischargeRoute: AuthenticatedIpdIdDischargeRoute,
}

const AuthenticatedIpdIdRouteWithChildren =
  AuthenticatedIpdIdRoute._addFileChildren(AuthenticatedIpdIdRouteChildren)

interface AuthenticatedIpdRouteChildren {
  AuthenticatedIpdIdRoute: typeof AuthenticatedIpdIdRouteWithChildren
  AuthenticatedIpdBedsRoute: typeof AuthenticatedIpdBedsRoute
  AuthenticatedIpdBirthRegisterRoute: typeof AuthenticatedIpdBirthRegisterRoute
  AuthenticatedIpdNewRoute: typeof AuthenticatedIpdNewRoute
  AuthenticatedIpdReportsRoute: typeof AuthenticatedIpdReportsRoute
  AuthenticatedIpdSettingsRoute: typeof AuthenticatedIpdSettingsRoute
  AuthenticatedIpdIndexRoute: typeof AuthenticatedIpdIndexRoute
}

const AuthenticatedIpdRouteChildren: AuthenticatedIpdRouteChildren = {
  AuthenticatedIpdIdRoute: AuthenticatedIpdIdRouteWithChildren,
  AuthenticatedIpdBedsRoute: AuthenticatedIpdBedsRoute,
  AuthenticatedIpdBirthRegisterRoute: AuthenticatedIpdBirthRegisterRoute,
  AuthenticatedIpdNewRoute: AuthenticatedIpdNewRoute,
  AuthenticatedIpdReportsRoute: AuthenticatedIpdReportsRoute,
  AuthenticatedIpdSettingsRoute: AuthenticatedIpdSettingsRoute,
  AuthenticatedIpdIndexRoute: AuthenticatedIpdIndexRoute,
}

const AuthenticatedIpdRouteWithChildren =
  AuthenticatedIpdRoute._addFileChildren(AuthenticatedIpdRouteChildren)

interface AuthenticatedLaboratoryRouteChildren {
  AuthenticatedLaboratoryIdRoute: typeof AuthenticatedLaboratoryIdRoute
  AuthenticatedLaboratoryNewRoute: typeof AuthenticatedLaboratoryNewRoute
  AuthenticatedLaboratoryTestsRoute: typeof AuthenticatedLaboratoryTestsRoute
  AuthenticatedLaboratoryIndexRoute: typeof AuthenticatedLaboratoryIndexRoute
}

const AuthenticatedLaboratoryRouteChildren: AuthenticatedLaboratoryRouteChildren =
  {
    AuthenticatedLaboratoryIdRoute: AuthenticatedLaboratoryIdRoute,
    AuthenticatedLaboratoryNewRoute: AuthenticatedLaboratoryNewRoute,
    AuthenticatedLaboratoryTestsRoute: AuthenticatedLaboratoryTestsRoute,
    AuthenticatedLaboratoryIndexRoute: AuthenticatedLaboratoryIndexRoute,
  }

const AuthenticatedLaboratoryRouteWithChildren =
  AuthenticatedLaboratoryRoute._addFileChildren(
    AuthenticatedLaboratoryRouteChildren,
  )

interface AuthenticatedOpdRouteChildren {
  AuthenticatedOpdAppointmentIdRoute: typeof AuthenticatedOpdAppointmentIdRoute
  AuthenticatedOpdAppointmentsRoute: typeof AuthenticatedOpdAppointmentsRoute
  AuthenticatedOpdBillingRoute: typeof AuthenticatedOpdBillingRoute
  AuthenticatedOpdConsultationRoute: typeof AuthenticatedOpdConsultationRoute
  AuthenticatedOpdRegistrationRoute: typeof AuthenticatedOpdRegistrationRoute
  AuthenticatedOpdReportsRoute: typeof AuthenticatedOpdReportsRoute
  AuthenticatedOpdSettingsRoute: typeof AuthenticatedOpdSettingsRoute
}

const AuthenticatedOpdRouteChildren: AuthenticatedOpdRouteChildren = {
  AuthenticatedOpdAppointmentIdRoute: AuthenticatedOpdAppointmentIdRoute,
  AuthenticatedOpdAppointmentsRoute: AuthenticatedOpdAppointmentsRoute,
  AuthenticatedOpdBillingRoute: AuthenticatedOpdBillingRoute,
  AuthenticatedOpdConsultationRoute: AuthenticatedOpdConsultationRoute,
  AuthenticatedOpdRegistrationRoute: AuthenticatedOpdRegistrationRoute,
  AuthenticatedOpdReportsRoute: AuthenticatedOpdReportsRoute,
  AuthenticatedOpdSettingsRoute: AuthenticatedOpdSettingsRoute,
}

const AuthenticatedOpdRouteWithChildren =
  AuthenticatedOpdRoute._addFileChildren(AuthenticatedOpdRouteChildren)

interface AuthenticatedOtRouteChildren {
  AuthenticatedOtIdRoute: typeof AuthenticatedOtIdRoute
  AuthenticatedOtReportsRoute: typeof AuthenticatedOtReportsRoute
  AuthenticatedOtScheduleRoute: typeof AuthenticatedOtScheduleRoute
  AuthenticatedOtSettingsRoute: typeof AuthenticatedOtSettingsRoute
  AuthenticatedOtIndexRoute: typeof AuthenticatedOtIndexRoute
}

const AuthenticatedOtRouteChildren: AuthenticatedOtRouteChildren = {
  AuthenticatedOtIdRoute: AuthenticatedOtIdRoute,
  AuthenticatedOtReportsRoute: AuthenticatedOtReportsRoute,
  AuthenticatedOtScheduleRoute: AuthenticatedOtScheduleRoute,
  AuthenticatedOtSettingsRoute: AuthenticatedOtSettingsRoute,
  AuthenticatedOtIndexRoute: AuthenticatedOtIndexRoute,
}

const AuthenticatedOtRouteWithChildren = AuthenticatedOtRoute._addFileChildren(
  AuthenticatedOtRouteChildren,
)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedPharmacyRouteChildren {
  AuthenticatedPharmacyMedicinesRoute: typeof AuthenticatedPharmacyMedicinesRoute
  AuthenticatedPharmacyIndexRoute: typeof AuthenticatedPharmacyIndexRoute
  AuthenticatedPharmacySalesNewRoute: typeof AuthenticatedPharmacySalesNewRoute
}

const AuthenticatedPharmacyRouteChildren: AuthenticatedPharmacyRouteChildren = {
  AuthenticatedPharmacyMedicinesRoute: AuthenticatedPharmacyMedicinesRoute,
  AuthenticatedPharmacyIndexRoute: AuthenticatedPharmacyIndexRoute,
  AuthenticatedPharmacySalesNewRoute: AuthenticatedPharmacySalesNewRoute,
}

const AuthenticatedPharmacyRouteWithChildren =
  AuthenticatedPharmacyRoute._addFileChildren(
    AuthenticatedPharmacyRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAmbulanceRoute: typeof AuthenticatedAmbulanceRoute
  AuthenticatedApiGatewayRoute: typeof AuthenticatedApiGatewayRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedAuditTrailRoute: typeof AuthenticatedAuditTrailRoute
  AuthenticatedAuthorityRoute: typeof AuthenticatedAuthorityRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRouteWithChildren
  AuthenticatedBillingCenterRoute: typeof AuthenticatedBillingCenterRoute
  AuthenticatedBiomedicalRoute: typeof AuthenticatedBiomedicalRoute
  AuthenticatedBloodBankRoute: typeof AuthenticatedBloodBankRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDialysisRoute: typeof AuthenticatedDialysisRoute
  AuthenticatedDischargeRoute: typeof AuthenticatedDischargeRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedIcuRoute: typeof AuthenticatedIcuRouteWithChildren
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedIpdRoute: typeof AuthenticatedIpdRouteWithChildren
  AuthenticatedLaboratoryRoute: typeof AuthenticatedLaboratoryRouteWithChildren
  AuthenticatedMobileApiRoute: typeof AuthenticatedMobileApiRoute
  AuthenticatedNurseStationRoute: typeof AuthenticatedNurseStationRoute
  AuthenticatedOpdRoute: typeof AuthenticatedOpdRouteWithChildren
  AuthenticatedOtRoute: typeof AuthenticatedOtRouteWithChildren
  AuthenticatedPacsRoute: typeof AuthenticatedPacsRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRouteWithChildren
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedQueueDisplayRoute: typeof AuthenticatedQueueDisplayRoute
  AuthenticatedRadiologyRoute: typeof AuthenticatedRadiologyRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityCenterRoute: typeof AuthenticatedSecurityCenterRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrEmployeesRoute: typeof AuthenticatedHrEmployeesRoute
  AuthenticatedHrLeaveRoute: typeof AuthenticatedHrLeaveRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAmbulanceRoute: AuthenticatedAmbulanceRoute,
  AuthenticatedApiGatewayRoute: AuthenticatedApiGatewayRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedAuditTrailRoute: AuthenticatedAuditTrailRoute,
  AuthenticatedAuthorityRoute: AuthenticatedAuthorityRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRouteWithChildren,
  AuthenticatedBillingCenterRoute: AuthenticatedBillingCenterRoute,
  AuthenticatedBiomedicalRoute: AuthenticatedBiomedicalRoute,
  AuthenticatedBloodBankRoute: AuthenticatedBloodBankRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDialysisRoute: AuthenticatedDialysisRoute,
  AuthenticatedDischargeRoute: AuthenticatedDischargeRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedIcuRoute: AuthenticatedIcuRouteWithChildren,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedIpdRoute: AuthenticatedIpdRouteWithChildren,
  AuthenticatedLaboratoryRoute: AuthenticatedLaboratoryRouteWithChildren,
  AuthenticatedMobileApiRoute: AuthenticatedMobileApiRoute,
  AuthenticatedNurseStationRoute: AuthenticatedNurseStationRoute,
  AuthenticatedOpdRoute: AuthenticatedOpdRouteWithChildren,
  AuthenticatedOtRoute: AuthenticatedOtRouteWithChildren,
  AuthenticatedPacsRoute: AuthenticatedPacsRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRouteWithChildren,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedQueueDisplayRoute: AuthenticatedQueueDisplayRoute,
  AuthenticatedRadiologyRoute: AuthenticatedRadiologyRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityCenterRoute: AuthenticatedSecurityCenterRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrEmployeesRoute: AuthenticatedHrEmployeesRoute,
  AuthenticatedHrLeaveRoute: AuthenticatedHrLeaveRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthCheckRoute: HealthCheckRoute,
  LoginRoute: LoginRoute,
  DischargeIdPrintRoute: DischargeIdPrintRoute,
  PatientCardIdPrintRoute: PatientCardIdPrintRoute,
  PrescriptionsIdPrintRoute: PrescriptionsIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
